export interface Chapter {
  slug: string;
  title: string;
  jumboText: string;
  number: number;
  description: string;
  accentVar: string;
  phase: "mvp" | "phase2";
}

export const CHAPTERS: Chapter[] = [
  {
    slug: "onboarding",
    title: "Oczekiwania autora",
    jumboText: "AUTORA",
    number: 1,
    description: "Kim jesteś jako twórca? Wywiad AI buduje Twój profil.",
    accentVar: "--k-ch-expectations",
    phase: "mvp",
  },
  {
    slug: "ai-w-filmie",
    title: "AI w filmie",
    jumboText: "AI",
    number: 2,
    description: "Jak AI zmienia branżę filmową? Narzędzia, etyka, możliwości.",
    accentVar: "--k-ch-ai",
    phase: "mvp",
  },
  {
    slug: "pomysl",
    title: "Pomysł",
    jumboText: "POMYSL",
    number: 3,
    description: "Skąd biorą się historie warte opowiedzenia?",
    accentVar: "--k-ch-idea",
    phase: "mvp",
  },
  {
    slug: "story",
    title: "Story",
    jumboText: "STORY",
    number: 4,
    description: "Jak rozwinąć pomysł w pełną historię filmową?",
    accentVar: "--k-ch-story",
    phase: "mvp",
  },
  {
    slug: "budzet",
    title: "Budżet",
    jumboText: "BUDZET",
    number: 5,
    description: "Jak zaplanować budżet studenckiego filmu?",
    accentVar: "--k-ch-budget",
    phase: "mvp",
  },
  {
    slug: "finansowanie",
    title: "Finansowanie",
    jumboText: "FINANS",
    number: 6,
    description: "Granty, crowdfunding, sponsorzy — skąd wziąć kasę?",
    accentVar: "--k-ch-finance",
    phase: "mvp",
  },
  {
    slug: "projekt",
    title: "Projekt",
    jumboText: "PROJKT",
    number: 7,
    description: "Zarządzanie projektem filmowym od A do Z.",
    accentVar: "--k-ch-project",
    phase: "mvp",
  },
  {
    slug: "technologia",
    title: "Technologia",
    jumboText: "TECHNO",
    number: 8,
    description: "Kamery, AI, software — narzędzia współczesnego filmowca.",
    accentVar: "--k-ch-tech",
    phase: "mvp",
  },
  {
    slug: "ludzie",
    title: "Ludzie",
    jumboText: "LUDZIE",
    number: 9,
    description: "Jak budować ekipę i pracować z ludźmi?",
    accentVar: "--k-ch-people",
    phase: "mvp",
  },
  {
    slug: "odbiorcy",
    title: "Grupa odbiorców",
    jumboText: "WIDZOW",
    number: 10,
    description: "Dla kogo robisz film? Zdefiniuj swoją publiczność.",
    accentVar: "--k-ch-audience",
    phase: "mvp",
  },
  {
    slug: "dystrybucja",
    title: "Kanały dystrybucji",
    jumboText: "DYSTRY",
    number: 11,
    description: "Festiwale, VOD, kina — jak dotrzeć do widza?",
    accentVar: "--k-ch-distribution",
    phase: "mvp",
  },
  {
    slug: "marketing",
    title: "Marketing",
    jumboText: "MARKET",
    number: 12,
    description: "Jak wypromować swój film?",
    accentVar: "--k-ch-marketing",
    phase: "mvp",
  },
  {
    slug: "monetyzacja",
    title: "Monetyzacja",
    jumboText: "PRZYCH",
    number: 13,
    description: "Jak zarabiać na filmach?",
    accentVar: "--k-ch-monetization",
    phase: "mvp",
  },
  {
    slug: "collabo",
    title: "Collabo",
    jumboText: "COLLBO",
    number: 14,
    description: "Kolaboracje, partnerstwa, co-produkcje.",
    accentVar: "--k-ch-collabo",
    phase: "mvp",
  },
  {
    slug: "dofinansowania",
    title: "Dofinansowania",
    jumboText: "GRANTY",
    number: 15,
    description: "Dofinansowania, edukacja, transparentność w akademii.",
    accentVar: "--k-ch-grants",
    phase: "mvp",
  },
  {
    slug: "open-source",
    title: "Open Source",
    jumboText: "OPEN",
    number: 16,
    description: "Open source w filmie — narzędzia i filozofia.",
    accentVar: "--k-ch-opensource",
    phase: "mvp",
  },
  {
    slug: "community",
    title: "Community",
    jumboText: "COMMUN",
    number: 17,
    description: "Budowanie społeczności wokół swojego kina.",
    accentVar: "--k-ch-community",
    phase: "mvp",
  },
];

export const MVP_CHAPTERS = CHAPTERS.filter((c) => c.phase === "mvp");
